---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role s3fs
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: s3fs | install system packages
  apt: pkg={{','.join(s3fs_debian_pkgs)}} state=present
  tags:
  - s3fs
  - install
  - update

- name: s3fs | fetch package
  get_url:
    url={{ s3fs_download_url }}/s3fs-{{ s3fs_version }}.tar.gz
    dest={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}.tar.gz
    
- name: s3fs | unzip package
  shell:
    /bin/tar zxvf s3fs-{{ s3fs_version }}.tar.gz
    chdir={{ s3fs_temp_dir }}
    creates={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}/configure
    
- name: s3fs | configure
  shell:
    ./configure
    chdir={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}
    creates={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}/config.status
    
- name: s3fs | make
  shell:
    /usr/bin/make
    chdir={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}
    creates={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}/src/s3cmd

- name: s3fs | make install
  shell:
    /usr/bin/make install
    chdir={{ s3fs_temp_dir }}/s3fs-{{ s3fs_version }}
    