#
# TODO: Needed while this repo is private
#
- name: analytics-server | upload ssh script
  copy: 
    src=git_ssh.sh dest=/tmp/git_ssh.sh 
    force=yes owner=root group=adm mode=750
  tags:
  - analytics-server
  - deploy
  - install
  - update

#
# TODO: Needed while this repo is private
#
- name: analytics-server | install read-only ssh key required for checkout
  copy: 
    src={{ as_git_identity_path }} dest=/etc/git-identity 
    force=yes owner=ubuntu group=adm mode=60
  tags:
  - analytics-server
  - deploy
  - install
  - update

- name: analytics-server | checkout code
  git: 
    dest={{ as_code_dir }} repo={{ as_source_repo }} 
    version={{ as_version }} force=true
  environment:
    GIT_SSH: /tmp/git_ssh.sh
    notify: analytics-server | restart the analytics service
  notify: analytics-server | start the analytics service
  tags:
    - analytics-server
    - deploy
    - install
    - update

#
# TODO: Needed while this repo is private
#
- name: analytics-server | update src permissions
  file: 
    path={{ as_code_dir }} state=directory owner={{ as_user }} 
    group={{ as_web_user }} mode=2750 recurse=yes
  tags:
  - analytics-server
  - deploy
  - install
  - update

#
# TODO: Needed while this repo is private
#
- name: analytics-server | remove read-only ssh key for the content repo
  file: path=/etc/git-identity state=absent
  tags:
  - analytics-server
  - deploy
  - install
  - update

#
# TODO: Needed while this repo is private
#
- name: analytics-server | remove ssh script
  file: path=/tmp/git_ssh.sh state=absent
  tags:
  - analytics-server
  - deploy
  - install
  - update

- name: analytics-server | install application requirements
  pip: 
    requirements={{ as_requirements_file }}
    virtualenv={{ as_venv_dir }} state=present
  sudo: true  
  sudo_user: "{{ as_user }}"
  notify: analytics-server | start the analytics service  
  tags:
  - analytics-server
  - deploy
  - install
  - update
