---

#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role analytics-server
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: analytics-server | install system packages
  apt: pkg={{','.join(as_debian_pkgs)}} state=present
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | create analytics-server user {{ as_user }}
  user: 
    name={{ as_user }} state=present shell=/bin/bash 
    home={{ as_home }} createhome=yes
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | setup the analytics-server env
  template: 
    src=opt/wwc/analytics-server/{{ as_env }}.j2
    dest={{ as_home }}/{{ as_env }} 
    owner="{{ as_user }}" group="{{ as_user }}"
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | drop a bash_profile
  copy: >
    src=../../common/files/bash_profile 
    dest={{ as_home }}/.bash_profile 
    owner={{ as_user }} 
    group={{ as_user }}


- name: analytics-server | ensure .bashrc exists
  shell: touch {{ as_home }}/.bashrc
  sudo: true  
  sudo_user: "{{ as_user }}"
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | add source of analytics-server_env to .bashrc
  lineinfile:
    dest={{ as_home }}/.bashrc
    regexp='. {{ as_home }}/analytics-server_env'    
    line='. {{ as_home }}/analytics_server_env'
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | add source venv to .bashrc
  lineinfile:
    dest={{ as_home }}/.bashrc
    regexp='. {{ as_venv_dir }}/bin/activate'    
    line='. {{ as_venv_dir }}/bin/activate'
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | install global python requirements
  pip: name={{ item }}
  with_items: as_pip_pkgs
  tags:
  - analytics-server
  - install
  - update

- name: analytics-server | create config
  template: 
    src=opt/wwc/analytics.auth.json.j2
    dest=/opt/wwc/analytics.auth.json 
    owner="{{ as_web_user }}" group="{{ as_web_user }}"
  tags:
  - analytics-server
  - install
  - update
  
- name: analytics-server | install service
  template:
    src=etc/init/analytics.conf.j2 dest=/etc/init/analytics.conf
    owner=root group=root

- include: deploy.yml    