---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Vars for role splunk
# 

#
# vars are namespace with the module name.
#
splunk_role_name: 'splunk'

#
# OS packages
#

splunk_debian_pkgs:
  - gdebi

splunk_redhat_pkgs: []

SPLUNKFORWARDER_LOG_ITEMS:
  - directory: '/mnt/logs/lms/edx.log'
    index: 'feanilsandbox-lms'

SPLUNKFORWARDER_SERVER: 'localhost:9997'

SPLUNKFORWARDER_PACKAGE_LOCATION: !!null
SPLUNKFORWARDER_DEB: !!null
SPLUNKFORWARDER_PASSWORD: !!null
splunkforwarder_output_dir: '/opt/splunkforwarder/'
