MEMORY = 2048
CPU_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box     = "edx-fullstack-zhTW"
  config.vm.box_url = "http://dl.minelab.tw/edX/vagrant-images/20131113-dosa-fullstack.box"

  config.vm.network :private_network, ip: "192.168.33.20"

  # Vagrant DNS config
  config.dns.tld = "dev"
  config.vm.hostname = "edx-fullstack-zhTW"
  config.dns.patterns = [/^.*edx.dev$/]

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]

    # You can adjust this to the amount of CPUs your system has available
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]
  end

  config.vm.provision :ansible do |ansible|
    # point Vagrant at the location of your playbook you want to run
    ansible.playbook = "../../../../playbooks-zhTW/vagrant-fullstack.yml"
    ansible.inventory_path = "../../../../playbooks-zhTW/vagrant/inventory.ini"
    ansible.verbose = "extra"
  end
end

# optional
VagrantDNS::Config.logger = Logger.new("dns.log")
