- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  vars_files:
    - "group_vars/all"
  roles:
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - edxlocal
    - mongo
    - { role: 'edxapp', EDXAPP_LMS_NGINX_PORT: 18030, EDXAPP_LMS_XML_NGINX_PORT: 80 }
