---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role task
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: task | install task specific system packages
  apt: pkg={{','.join(task_debian_pkgs)}} state=present
  tags:
  - task
  - install
  - update

- name: task | create s3fs mount points
  file:
    path={{ item.mount_point }} owner={{ item.owner }}
    group={{ item.group }} mode={{ item.mode }} state="directory"
  with_items: "{{ task_s3fs_mounts }}"

- name: task | mount s3 buckets
  mount:
    name={{ item.mount_point }} src={{ item.bucket }} fstype=fuse.s3fs
    opts=use_cache=/tmp,iam_role={{ task_iam_role }} state=mounted
  with_items: "{{ task_s3fs_mounts }}"

  
#- name: task | mount s3 buckets
#  shell:
#    /usr/local/bin/s3fs {{ item.bucket }} {{ item.mount_point }} -ouse_cache=/tmp,iam_role={{ task_iam_role }}
#  with_items: "{{ task_s3fs_mounts }}"
